### ISSUE TITLE
Cal que el desxifat  estigui en JS? 

### ISSUE THREAD

**Issue by carlesm** [onvotar-bot/onvotar-base#1]
El procés de llençar un nodejs per executar el desxifrat castiga molt, no el podem mirar de refer en python nadiu?

**Comment by masipcat** [comment]
+1

**Comment by pokoli** [comment]
Fa una mica de coisor als ulls!!!!

**Comment by iordic** [comment]
Es deu de poder amb la llibreria de pyCrypto. 
I el fragment de codi:
```python
letter_num = int(dni_num/23)
letter_num *= 23
letter_num = dni_num-letter_num
```
Es pot cambiar per:
```python
letter_num = dni_num % 23
```

**Comment by carlesm** [comment]
No és que faci cosa mirar-te el javascript (que també), és una qüestiò d'eficiencia, no arrancar 1 procés de shell+1 procés de nodejs cada consulta.

O fer el bot directament en nodejs....

**Comment by iordic** [comment]
Crec que ho tinc. Pareix que funciona amb este codi:
```python
from Crypto.Cipher import AES

def EVP_BytesToKey(password, salt, key_len, iv_len):
    """
    Derive the key and the IV from the given password and salt.
    """    
    dtot =  hashlib.md5(password + salt).digest()
    d = [dtot]
    while len(dtot)<(iv_len+key_len):
        d.append(hashlib.md5(d[-1] + password + salt).digest())
        dtot += d[-1]
    return dtot[:key_len], dtot[key_len:key_len+iv_len]


def _decrypt(text, password):
    # crypto.createDecipher() no gasta salt:
    key, iv = EVP_BytesToKey(password, '', 32, 16)
    decipher = AES.new(key, AES.MODE_CBC, iv)
    return decipher.decrypt(text.strip().decode("hex")).decode('utf-8')
```
Sería canviar la funció _decrypt() per eixa, crear la funció EVP_BytesToKey() (trobada a internet) en el fitxer calculate.py. També faría falta tindre instalat pyCrypto.

**Comment by iordic** [comment]
No, amb python2.7. Vaig a vore sí ho conseguisc amb python3.

**Comment by iordic** [comment]
Amb python3 em funciona amb este codi (en debian, no aconseguia instalar pycrypto a windows :/ ):
```python
def EVP_BytesToKey(password, salt, key_len, iv_len):
    dtot = hashlib.md5((password + salt).encode()).digest()
    d = [dtot]
    while len(dtot) < (iv_len + key_len):
        d.append(hashlib.md5(d[-1] + (password + salt).encode()).digest())
        dtot = dtot + d[-1]
    return dtot[:key_len], dtot[key_len:key_len+iv_len]


def _decrypt(text, password):
    # crypto.createDecipher() no gasta salt:
    key, iv = EVP_BytesToKey(password, '', 32, 16)
    decipher = AES.new(key, AES.MODE_CBC, iv)
    return decipher.decrypt(bytes.fromhex(text.strip()))
```
Si algú te pycrypto instalat a windows podria provar-ho.

**Comment by iordic** [comment]
He gastat el pyCryptodome, es veu que el pyCrypto està deprecated i no funciona amb python 3.6. I m'ha funcionat.
